Tag various character arrays with NJS_NONSTRING.
In njs we have a number of character arrays which are intentionally not
NUL terminated.

With GCC 15 this

  static const u_char  hex[16] = "0123456789ABCDEF";

will trigger a warning (which we treat as an error) like

  src/njs_string.h: In function ‘njs_string_encode’:
  src/njs_string.h:212:36: error: initializer-string for array of ‘unsigned char’ truncates NUL terminator but destination lacks ‘nonstring’ attribute (17 chars into 16 available) [-Werror=unterminated-string-initialization]
    212 |     static const u_char  hex[16] = "0123456789ABCDEF";
        |                                    ^~~~~~~~~~~~~~~~~~

By adding NJS_NONSTRING like

  static const u_char  hex[16] NJS_NONSTRING = "0123456789ABCDEF";

we no longer get the warning.

Closes: https://github.com/nginx/njs/issues/857
Signed-off-by: Andrew Clayton <a.clayton@nginx.com>